### ISSUE TITLE
Improve bower registry loading

### ISSUE THREAD

**Issue by albertinad** [albertinad/brackets-bower#21]
Loading the bower registry for the first time or when it's time to refresh it takes too long. It could use the default bower cache to show some results until the registry is fully load, so the user can browse while loading it.

**Comment by erknrio** [comment]
Hello Albertina,

There is any option to load registry on demand? For example: first time loading take a lot of time. If I want to install bootstrap, jquery etc. I don't need all the registry. Maybe, you can make an AJAX call to get this packages without loading all the registry.

Sorry for my english :(.
