### ISSUE TITLE
Option to view and remove installed packages

### ISSUE THREAD

**Issue by navelpluisje** [albertinad/brackets-bower#29]
Create a panel for listing and removing already installed packages

**Comment by albertinad** [comment]
Installed packages can be displayed in the DependenciesView.

**Comment by navelpluisje** [comment]
Why not showing both DependenciesView and ConfigurationView in one panel? They both do almost the same and I think it's pretty logical to have them together. 
Create a InstalledPackagesView for the already installed packages.
Makes more sense to me.

**Comment by albertinad** [comment]
Right now makes sense what you said, but I have planned t use the ConfigurationView to also display to populate a list with the configuration available and edit the file through the UI, instead of only open the .bowerrc file in the active editor.

**Comment by navelpluisje** [comment]
Ok. But doesn't it make sense to do the same for json file also? And create an extra panel?

**Comment by albertinad** [comment]
Yes, that's planned for the future, but that's ok if you want to implement this feature in an extra panel.
I will make a few changes:
* DependenciesView will be renamed to BowerJsonView, when it has the focus it will display some commands like install, update and remove at the main panel header.
Now it makes sense what it actually do and will do that panel.
Let's do the extra panel InstalledPackagesView.

**Comment by albertinad** [comment]
I'm changing the way PanelView handle its panel, so don't worry about some bad behavior when switching panels. It's under current development, in a few hours I will push those changes, since they are necessary  I'm doing it in the master branch, keep your fork in sync.
