### ISSUE TITLE
Uncaught TypeError: Cannot read property [pkg_name] of undefined - on update

### ISSUE THREAD

**Issue by thco** [albertinad/brackets-bower#47]
Hi.

With the newest version, when I click on the update button to update a package to the latest version, I got this : 

```
// From BowerJson.js line 87
Uncaught TypeError: Cannot read property 'lodash' of undefined
```

Can you take a look at this ?

Thanks !

**Comment by albertinad** [comment]
Hi! sure, thanks!

**Comment by albertinad** [comment]
Hi @thco , the new version of the extension with the fix for this bug is ready at the brackets registry. Please, check if the issue remains, if not feel free to close the issue :)
Thanks!

**Comment by albertinad** [comment]
Closing issue, if the issue persists feel free to open it.

**Comment by thco** [comment]
Works like a charm ! Thank you :)

I just notice that I got an notification error while update Bootstrap, for exemple. I don't think it's related to your extension btw, so let's close ! :+1: You rock
