### ISSUE TITLE
Doesn't detect existing bower components

### ISSUE THREAD

**Issue by MartinJBates** [albertinad/brackets-bower#52]
Hi, 

I have existing bower components in my working folder root, but when I open the bower panel, it says no packages are installed. Shouldn't this detect already installed/existing packages? See below for a screenshot.

![image](https://cloud.githubusercontent.com/assets/4522738/7116235/e873e888-e1e7-11e4-9331-5e886a834fbc.png)

**Comment by MartinJBates** [comment]
Update: if I install a package via the panel it appears in the bower.json file and at the bottom. if I uninstall it removes it from the panel and the bower.json file

**Comment by albertinad** [comment]
Hi, 
For the current implementation if the bower components are located at the root project, it should be able to find them. Unless, you're under lower internet connectivity, I didn't release yet the new version that fixes that. Can you share me the log file? it should be placed under your home directory, 'brackets-bower.log'

**Comment by MartinJBates** [comment]
my structure is:

root (MySite)
- bower.json
- bower_components/
- node_modules/

I can't find that .log file you're requesting.

**Comment by albertinad** [comment]
Ok, today I will upload a new version including those changes and then we can try again with the same project. Another question, which version of brackets-bower are you using? Did you try again multiple times to see if you can reproduce it? I can't reproduce it, only if I have low internet connectivity or bower is not working right? What can be happening is that, I use a the `list` bower command to get the current dependencies with or without bower.json and that command also gets the latest updates. So that can be failing, if something happens that bower cannot get updates, the entire command fails, even when it gets the current dependencies. There's an option for that command, to only get installed dependencies in offline mode, without getting latest updates. That's the fix I implemented, as soon as I upload it to the registry I will let you know. 
Thanks for reporting this!

**Comment by MartinJBates** [comment]
It says I'm using version 0.2.5. I've tried numerous times and it won't show what's within my existing bower.json file. If I install/remove via your extension then it shows in the panel/updates the bower.json file successfully.

It can also load the bower registry successfully.

**Comment by albertinad** [comment]
And it says something in the Dev Tools console?

**Comment by MartinJBates** [comment]
I get this in dev tools (which could be due to being behind a corporate restricted internet) but here for you to look at:

![image](https://cloud.githubusercontent.com/assets/4522738/7117465/b7614318-e1f0-11e4-8ddb-5c6a1b52b1c0.png)

**Comment by albertinad** [comment]
Thanks! It confirms part of my suspicions, relate to the list command. I will research a little more on that specific error and let you know when everything is ready. 
Thanks!

**Comment by MartinJBates** [comment]
Okay great - no problems!

**Comment by albertinad** [comment]
Hi @MartinJBates , I'm having issues uploading the extension, in the mean time, you can manually download the zip file for the latest version and manually add it to brackets,
https://github.com/albertinad/brackets-bower/releases/tag/v0.2.6

Let me know if the problem wasn't fixed.

Thanks!

**Comment by MartinJBates** [comment]
Hi, this now detects the list of installed bower components successfully. Perhaps as a UI suggestion, there should be an input field to search for bower components in the bower ui where it lists the installed components or a search button?

**Comment by albertinad** [comment]
Great! that input field to search would be browse the installed components or the bower registry/other registries? if you mean the last option, you can search for components using a Quick Open style interface. But, I would like to improve the search by adding an option/UI to the panel.
Thanks!

**Comment by MartinJBates** [comment]
Yeah I meant by having a search field to search for new bower components directly in the UI of the panel that shows what's installed/ready to update etc as it would provide relevant access to get additional packages.

**Comment by albertinad** [comment]
Great! I created an issue for that #55 Since the other issue was related with QuickInstall feature. Thanks! That would be a great improvement.
