### ISSUE TITLE
How to install : Polymer/core-list#^0.5

### ISSUE THREAD

**Issue by sander76** [albertinad/brackets-bower#53]
Working with Polymer and trying to install some elements from Bower.
From the command line I need to type

bower install Polymer/core-list#^0.5

using "install From Bower" and typing "+Polymer/core-list" does not yield any result.
Anyone a suggestion ?

Sander.

**Comment by albertinad** [comment]
Hi @sander76 ! "install from Bower" browse the Bower default registry, and it seems that the polymer component that you want is not registered at the default registry, that's the reason why you don't see any result.
You can create a bower.json file, using the bower panel actions. Then add the component like the following:
```{
  "name": your-app",
  "dependencies": {
    "polymer": "0.5.5",
    "polymer-core-list": "Polymer/core-list#^0.5"
  }
}
```
Then execute the command `install` from the panel header buttons. This will install polymer (it will get the information from the registry) and install core-list by downloading the given git tag.

The current search implementation will be improved in future release.
Let me know if that works for you.
