### ISSUE TITLE
Feature Request: Use bower.json outside of root

### ISSUE THREAD

**Issue by shaneparsons** [albertinad/brackets-bower#58]
Just thought it'd be great to be able to use / point to the bower.json from a **sub-directory** 

**(ex. src/ bower.json)**

As it stands now, doing so just leads to a **bower.json not found!**

**Comment by albertinad** [comment]
Hi @shaneparsons ! That feature is implemented in the last version. I'm having issues to uploading it to the brackets registry, but you can manually (download)[] it and drag it to the extension manager (or unzip it to the brackets extensions users folder).
By default, the extension will take as current working directory, your current project root path, to change it you just need to go to the project tree viewer panel, click on the folder you want to set as the current working directory
- if you select a folder, it will take that folder path as the current working directory for the extension
- if you select a file, it will take the file parent folder as the current working directory for the extension
- to set the project root as the cwd, right click on an empty space in the project tree viewer panel, or a top level file

Let me know if that works for you.

Thanks!
![bower-001](https://cloud.githubusercontent.com/assets/2309921/7454915/92d8feaa-f24e-11e4-8407-a2bfdda55441.png)

**Comment by shaneparsons** [comment]
Perfect, works great!
