### ISSUE TITLE
Brackets-bower while installing dependecies not considering .bowerrc file directory property, always installing dependencies  in bower_components folder

### ISSUE THREAD

**Issue by ravibharathii** [albertinad/brackets-bower#59]
Brackets-bower installing dependencies always in bower_components folder,even though there is a.bowerrc file and entry for directory property .

My .bowerrc file at the root of my project looks like
{
    "directory": "lib",
    "proxy": "http://http.proxy.xxx.com:yyyy",
    "https-proxy": "https://http.proxy.xxx.com:yyyy"
}

I tried bower install command through command line, it worked.

**Comment by albertinad** [comment]
Hi @ravibharathii , I'm having issues uploading the extension to brackets registry. This bug must be fixed already in (this)[https://github.com/albertinad/brackets-bower/releases/tag/v0.2.9] version. Please, download it and add it manually to brackets. Let me know if this bug persists.

Thanks!

**Comment by ravibharathii** [comment]
Thanks for the reply . It worked for me after updating the plugin.

**Comment by albertinad** [comment]
Great! closing the issue.
